apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: p7r3nhjkx-nodejs 
  janus-idp.io/tekton: p7r3nhjkx-nodejs
  backstage.io/kubernetes-id: p7r3nhjkx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p7r3nhjkx-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  